# Use postgres/example user/password credentials
version: '3.1'

services:
  server:
    image: app-server
    restart: unless-stopped
    build: server/.
    ports:
      - '3200:3200'

  client:
    image: app-client
    restart: unless-stopped
    build: client/.
    ports:
      - '80:80'

  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   ports:
  #     - 5432:5432
